name: Publish App
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        working-directory: .
        run: npm install
      
      - name: Build
        working-directory: .
        run: npm run build
                      
      - name: Domain
        working-directory: .
        run: echo 'margarettahouse.com' > dist/CNAME

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}" 
